kind: Deployment
apiVersion: apps/v1
metadata:
  name: exam-chart
  
  namespace: mychart
  labels:
    app.kubernetes.io/instance: exam-chart
    app.kubernetes.io/name: exam-chart
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/instance: exam-chart
      app.kubernetes.io/name: exam-chart
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: exam-chart
        app.kubernetes.io/name: exam-chart
    spec:
      containers:
        - resources: {}
          name: exam-chart
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

          readinessProbe:
            httpGet:
              path: /ready
              port: http
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          securityContext: {}

          
          imagePullPolicy: IfNotPresent
          image: 'quay.io/leandrop02/ex288-chart:1.0'

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%