kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: myapp
  labels:
    app.kubernetes.io/instance: myapp
    app.kubernetes.io/name: myapp

spec:
  to:
    kind: Service
    name: myapp
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None